services:
  cuda_container:
    container_name: transformer
    image: nvidia/cuda:12.2.0-base-ubuntu22.04
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/data
      - ./model:/model
      - ./src:/src
      - ./logs:/logs
    working_dir: /app
    command: python3 ./train_transformer.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
